//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanTup.GPlusNotifier {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DanTup.GPlusNotifier.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About.
        /// </summary>
        internal static string AboutLink {
            get {
                return ResourceManager.GetString("AboutLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About G+ Notifier.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error retrieving notifications from Google+..
        /// </summary>
        internal static string ApplicationErrorMessage {
            get {
                return ResourceManager.GetString("ApplicationErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ApplicationErrorTitle {
            get {
                return ResourceManager.GetString("ApplicationErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G+ Notifier.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G+ Notifier successfully updated to version {0}..
        /// </summary>
        internal static string ApplicationUpdatedMessage {
            get {
                return ResourceManager.GetString("ApplicationUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G+ Notifier Updated!.
        /// </summary>
        internal static string ApplicationUpdatedTitle {
            get {
                return ResourceManager.GetString("ApplicationUpdatedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic Updates.
        /// </summary>
        internal static string AutomaticUpdatesGroupText {
            get {
                return ResourceManager.GetString("AutomaticUpdatesGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No thanks, just alert me.
        /// </summary>
        internal static string AutomaticUpdatesNo {
            get {
                return ResourceManager.GetString("AutomaticUpdatesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When new versions of G+ Notifier are available, would you like to install them automatically?.
        /// </summary>
        internal static string AutomaticUpdatesText {
            get {
                return ResourceManager.GetString("AutomaticUpdatesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, automatically install new versions.
        /// </summary>
        internal static string AutomaticUpdatesYes {
            get {
                return ResourceManager.GetString("AutomaticUpdatesYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Close.
        /// </summary>
        internal static string CloseButtonText {
            get {
                return ResourceManager.GetString("CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributions from:.
        /// </summary>
        internal static string ContributionsFromLabel {
            get {
                return ResourceManager.GetString("ContributionsFromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by:.
        /// </summary>
        internal static string CreatedByLabel {
            get {
                return ResourceManager.GetString("CreatedByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Donate.
        /// </summary>
        internal static string DonateLink {
            get {
                return ResourceManager.GetString("DonateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading and installing version {0} of G+ Notifier....
        /// </summary>
        internal static string DownloadingNewVersionMessage {
            get {
                return ResourceManager.GetString("DownloadingNewVersionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to write to the folder G+ Notifier is installed in. Automatic updates will be unavailable..
        /// </summary>
        internal static string ErrorUnableToWrite {
            get {
                return ResourceManager.GetString("ErrorUnableToWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic updates are not supported on this version of Windows :-(.
        /// </summary>
        internal static string ErrorUnsupportedOS {
            get {
                return ResourceManager.GetString("ErrorUnsupportedOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string ExitLink {
            get {
                return ResourceManager.GetString("ExitLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Feedback &amp;&amp; Support.
        /// </summary>
        internal static string FeedbackLink {
            get {
                return ResourceManager.GetString("FeedbackLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Google+ in my default browser.
        /// </summary>
        internal static string IconBehaviourBrowser {
            get {
                return ResourceManager.GetString("IconBehaviourBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Behaviour.
        /// </summary>
        internal static string IconBehaviourGroupText {
            get {
                return ResourceManager.GetString("IconBehaviourGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the compact Notifications window.
        /// </summary>
        internal static string IconBehaviourNotifications {
            get {
                return ResourceManager.GetString("IconBehaviourNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When I click the G+ Notifier icon in the notification area....
        /// </summary>
        internal static string IconBehaviourText {
            get {
                return ResourceManager.GetString("IconBehaviourText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Install Update.
        /// </summary>
        internal static string InstallUpdateLink {
            get {
                return ResourceManager.GetString("InstallUpdateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Login.
        /// </summary>
        internal static string LoginLink {
            get {
                return ResourceManager.GetString("LoginLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login to your Google Plus account below. 
        ///This window will disappear once your account is connected..
        /// </summary>
        internal static string LoginText {
            get {
                return ResourceManager.GetString("LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Logout.
        /// </summary>
        internal static string LogoutLink {
            get {
                return ResourceManager.GetString("LogoutLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have 1 unread notification in Google+!.
        /// </summary>
        internal static string NewNotificationMessage {
            get {
                return ResourceManager.GetString("NewNotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} unread notifications in Google+!.
        /// </summary>
        internal static string NewNotificationsMessage1234 {
            get {
                return ResourceManager.GetString("NewNotificationsMessage1234", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} unread notifications in Google+!.
        /// </summary>
        internal static string NewNotificationsMessage5plus {
            get {
                return ResourceManager.GetString("NewNotificationsMessage5plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Notifications.
        /// </summary>
        internal static string NewNotificationsTitle {
            get {
                return ResourceManager.GetString("NewNotificationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new version of G+ Notifier available. You have version {0}, but version {1} is available..
        /// </summary>
        internal static string NewVersionAvailableMessage {
            get {
                return ResourceManager.GetString("NewVersionAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G+ Notifier Update Available.
        /// </summary>
        internal static string NewVersionAvailableTitle {
            get {
                return ResourceManager.GetString("NewVersionAvailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no unread notifications in Google+..
        /// </summary>
        internal static string NoNewNotificationsMessage {
            get {
                return ResourceManager.GetString("NoNewNotificationsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Notifications.
        /// </summary>
        internal static string NoNewNotificationsTitle {
            get {
                return ResourceManager.GetString("NoNewNotificationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string OkButtonText {
            get {
                return ResourceManager.GetString("OkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (recommended).
        /// </summary>
        internal static string RecommendedText {
            get {
                return ResourceManager.GetString("RecommendedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Settings.
        /// </summary>
        internal static string SettingsLink {
            get {
                return ResourceManager.GetString("SettingsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G+Notifier Settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Twitter.
        /// </summary>
        internal static string TwitterLink {
            get {
                return ResourceManager.GetString("TwitterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G+ Notifier {0}.
        /// </summary>
        internal static string VersionText {
            get {
                return ResourceManager.GetString("VersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G+Notifier &amp;Website.
        /// </summary>
        internal static string WebsiteLink {
            get {
                return ResourceManager.GetString("WebsiteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G+Notifier &amp;Website - Update available!.
        /// </summary>
        internal static string WebsiteUpdateLink {
            get {
                return ResourceManager.GetString("WebsiteUpdateLink", resourceCulture);
            }
        }
    }
}
